version: '3.2'

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}

  redis:
    image: 'bitnami/redis:latest'
    container_name: redis
    environment:
      # - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    restart: always
    ports:
      - 6379:6379

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    links:
      - db
    ports:
      - 8888:80
    environment:
      PMA_ARBITRARY: 1
    depends_on:
      - db

volumes:
  data:
